version: 2

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - id: default
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

  - id: android
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=1
      - CC={{ .Env.ANDROID_NDK_HOME }}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
      - CXX={{ .Env.ANDROID_NDK_HOME }}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++
    goos:
      - android
    goarch:
      - arm64

archives:
  - id: default
    builds: [default]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format: zip
    files:
      - none*

  - id: android
    builds: [android]
    name_template: "{{ .ProjectName }}_{{ .Version }}_Android_{{ .Arch }}"
    format: zip
    files:
      - none*

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'Merge pull request'
      - 'Merge branch'

release:
  disable: '{{ eq .Env.SNAPSHOT "true" }}'