name: goreleaser

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'snapshot'
        type: choice
        options:
          - snapshot
          - release

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          cache: true

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses || true

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c

      - name: Set Android NDK environment variables
        run: |
          echo "ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
          echo "ANDROID_NDK=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
          echo "${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: ${{ github.event_name == 'push' && 'release --clean' || 'build --snapshot' }}
        env:
          GITHUB_TOKEN: ${{ secrets.WF_TOKEN }}
          SNAPSHOT: ${{ github.event_name != 'push' }}

      - name: Display structure of dist directory
        run: ls -R dist/

      - name: Upload all artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-builds
          path: dist/*
          retention-days: 5
        if: always()

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-builds
          path: dist/android_android_arm64/*
          retention-days: 5
        if: always()

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-builds
          path: dist/default_windows_amd64_v1/*
          retention-days: 5
        if: always()

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-builds
          path: |
            dist/default_linux_amd64_v1/*
            dist/default_linux_arm64/*
          retention-days: 5
        if: always()

      - name: Upload Darwin artifacts
        uses: actions/upload-artifact@v4
        with:
          name: darwin-builds
          path: |
            dist/default_darwin_amd64_v1/*
            dist/default_darwin_arm64/*
          retention-days: 5
        if: always()